export enum i5Genero {
  AVENTURA = "AVENTURA",
  CIENCIA_FICCION = "CIENCIA_FICCION",
  FANTASIA = "FANTASIA",
  ROMANCE = "ROMANCE",
  MISTERIO = "MISTERIO",
  BIOGRAFICO = "BIOGRAFICO",
  HISTORIA = "HISTORIA",
  AUTOAYUDA = "AUTOAYUDA"
}
