export enum Genero {
AVENTURA = 'AVENTURA',
CIENCIA_FICCION = 'CIENCIA FICCIÓN',
FANTASIA = 'FANTASÍA',
ROMANCE = 'ROMANCE',
MISTERIO = 'MISTERIO',
BIOGRAFICO = 'BIOGRÁFICO',
HISTORIA = 'HISTORIA',
AUTOAYUDA = 'AUTOAYUDA',
}
